# Generated by Django 2.1.7 on 2019-03-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ac_login', '0001_initial'),
        ('ac_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenRegister',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact_number', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='citizen/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_login.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Compliants',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='compliants/')),
                ('register_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('closing_date', models.DateField()),
                ('ctid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_citizen.CitizenRegister')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_admin.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='feedback/')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_citizen.Compliants')),
                ('ctid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_citizen.CitizenRegister')),
            ],
        ),
    ]
