# Generated by Django 2.1.7 on 2019-03-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ac_admin', '0001_initial'),
        ('ac_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='officer',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='officer/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_admin.department')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_login.login')),
            ],
        ),
    ]
